import type { User } from "../component/columns";

export const mockData: User[] = [
  {
    key: "1",
    id: "4821",
    name: "John Doe",
    role: "Admin",
    email: "john.doe@example.com",
    status: "Active",
    joinedDate: "2024-01-15",
  },
  {
    key: "2",
    id: "9375",
    name: "Jane Smith",
    role: "User",
    email: "jane.smith@example.com",
    status: "Active",
    joinedDate: "2024-02-20",
  },
  {
    key: "3",
    id: "6043",
    name: "Bob Johnson",
    role: "Manager",
    email: "bob.johnson@example.com",
    status: "Inactive",
    joinedDate: "2024-03-10",
  },
  {
    key: "4",
    id: "2816",
    name: "Emily Brown",
    role: "User",
    email: "emily.brown@example.com",
    status: "Active",
    joinedDate: "2024-03-25",
  },
  {
    key: "5",
    id: "7509",
    name: "Michael Wilson",
    role: "Admin",
    email: "michael.wilson@example.com",
    status: "Active",
    joinedDate: "2024-04-08",
  },
  {
    key: "6",
    id: "1182",
    name: "Sarah Miller",
    role: "Manager",
    email: "sarah.miller@example.com",
    status: "Inactive",
    joinedDate: "2024-04-20",
  },
  {
    key: "7",
    id: "5469",
    name: "David Taylor",
    role: "User",
    email: "david.taylor@example.com",
    status: "Active",
    joinedDate: "2024-05-02",
  },
  {
    key: "8",
    id: "8324",
    name: "Olivia Anderson",
    role: "User",
    email: "olivia.anderson@example.com",
    status: "Active",
    joinedDate: "2024-05-15",
  },
  {
    key: "9",
    id: "2937",
    name: "William Thomas",
    role: "Manager",
    email: "william.thomas@example.com",
    status: "Inactive",
    joinedDate: "2024-06-05",
  },
  {
    key: "10",
    id: "4765",
    name: "Ava Jackson",
    role: "User",
    email: "ava.jackson@example.com",
    status: "Active",
    joinedDate: "2024-06-18",
  },
  {
    key: "11",
    id: "5198",
    name: "Ethan White",
    role: "Admin",
    email: "ethan.white@example.com",
    status: "Active",
    joinedDate: "2024-07-01",
  },
  {
    key: "12",
    id: "3042",
    name: "Mia Harris",
    role: "Manager",
    email: "mia.harris@example.com",
    status: "Inactive",
    joinedDate: "2024-07-13",
  },
  {
    key: "13",
    id: "6721",
    name: "Noah Martin",
    role: "User",
    email: "noah.martin@example.com",
    status: "Active",
    joinedDate: "2024-08-03",
  },
  {
    key: "14",
    id: "8854",
    name: "Isabella Lee",
    role: "User",
    email: "isabella.lee@example.com",
    status: "Active",
    joinedDate: "2024-08-21",
  },
  {
    key: "15",
    id: "1486",
    name: "Lucas Walker",
    role: "Manager",
    email: "lucas.walker@example.com",
    status: "Inactive",
    joinedDate: "2024-09-09",
  },
  {
    key: "16",
    id: "9573",
    name: "Amelia Hall",
    role: "Admin",
    email: "amelia.hall@example.com",
    status: "Active",
    joinedDate: "2024-09-23",
  },
  {
    key: "17",
    id: "4238",
    name: "Benjamin Young",
    role: "User",
    email: "benjamin.young@example.com",
    status: "Active",
    joinedDate: "2024-10-05",
  },
  {
    key: "18",
    id: "7319",
    name: "Harper King",
    role: "User",
    email: "harper.king@example.com",
    status: "Inactive",
    joinedDate: "2024-10-18",
  },
  {
    key: "19",
    id: "6097",
    name: "Elijah Scott",
    role: "Manager",
    email: "elijah.scott@example.com",
    status: "Active",
    joinedDate: "2024-11-02",
  },
  {
    key: "20",
    id: "2741",
    name: "Charlotte Green",
    role: "User",
    email: "charlotte.green@example.com",
    status: "Active",
    joinedDate: "2024-11-20",
  },
];
